// <auto-generated />
namespace MediaLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddRequiredToArtist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRequiredToArtist));
        
        string IMigrationMetadata.Id
        {
            get { return "201801300509477_AddRequiredToArtist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
